src/scrap/urls.py
from django.urls import path
from . import views

app_name = 'scrap'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('list/', views.list_view, name='list_view'),
]

src/work_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls', namespace='scrap')),
    path('', include('accounts.urls', namespace='accounts'))
]

src/scrap/models.py
from django.db import models
import jsonfield


def default_url():
    return {'work': '', 'dou': '', 'djinni': ''}


class City(models.Model):
    name = models.CharField(max_length=50, blank=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=50, blank=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    url = models.URLField(unique=True)
    title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    description = models.TextField()
    city = models.ForeignKey('City', on_delete=models.CASCADE)
    language = models.ForeignKey('Language', on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Vacancy'
        verbose_name_plural = 'Vacancies'
        ordering = ['-timestamp']

    def __str__(self):
        return self.title


class Url(models.Model):
    city = models.ForeignKey('City', on_delete=models.CASCADE)
    language = models.ForeignKey('Language', on_delete=models.CASCADE)
    url = jsonfield.JSONField(default=default_url)
    
    class Meta:
        unique_together = ('city', 'language')
    

src/scrap/forms.py
from django import forms
from .models import City, Language


class FindForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name='slug', required=False,
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='slug', required=False,
                                      widget=forms.Select(attrs={'class': 'form-control'}))

src/scrap/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Vacancy
from .forms import FindForm


def home_view(request):
    form = FindForm()

    context = {
        'form': form
    }

    return render(request, 'scrap/vacancies/home.html', context=context)


def list_view(request):
    vacancies = Vacancy.objects.all()

    if request.method == 'GET':
        form = FindForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            # print(cd)
            if cd['city'] and cd['language']:
                vacancies = Vacancy.objects.filter(city__name=cd['city'], language__name=cd['language'])
            elif cd['language']:
                vacancies = Vacancy.objects.filter(language__name=cd['language'])
            elif cd['city']:
                vacancies = Vacancy.objects.filter(city__name=cd['city'])
            else:
                vacancies = Vacancy.objects.all()
            # print(vacancies)
    else:
        form = FindForm()

    paginator = Paginator(vacancies, 10)
    page_number = request.GET.get('page', 1)
    vacancies = paginator.page(page_number)

    context = {
        'object_list': vacancies,
        'form': form
    }

    return render(request, 'scrap/vacancies/list.html', context=context)

src/scrap/templates/scrap/vacancies/home.html
{% extends 'scrap/base.html' %}

{% block title %}Home{% endblock%}

{% block content %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <form method="GET" action="{% url 'scrap:list_view' %}">
            <div class="mb-3">
                {{ form.as_p }}
                <!--{% csrf_token %}-->
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<!--<form method="post" action="">-->
<!--    {{ form.as_p }}-->
<!--    {% csrf_token %}-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->
{% endblock %}

src/scrap/templates/scrap/vacancies/list.html
{% extends 'scrap/base.html' %}

{% block title %}Vacancies{% endblock%}

{% block content %}
    {% for vacancy in object_list %}
        <div class="card my-3">
            <div class="card-header">
                <h5><a href="{{ vacancy.url }}">{{ vacancy.title }}</a></h5>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ vacancy.company }}</h5>
                <p class="card-text">{{ vacancy.description }}</p>
                <p>{{ vacancy.city.name }} | {{ vacancy.language.name }} | {{ vacancy.timestamp|date:"d-m-Y" }}</p>
                <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
            </div>
        </div>
    {% endfor %}
    <div class="pagination">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    {% if object_list.has_previous %}
                        <a class="page-link" href="?city={{form.cleaned_data.city}}&language={{form.cleaned_data.language}}&page={{ object_list.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>
                {% for page in object_list.paginator.page_range %}
                    <li class="page-item
                        {% if page == object_list.number %}
                            active
                        {% endif %}">
                            <a class="page-link" href="?city={{form.cleaned_data.city}}&language={{form.cleaned_data.language}}&page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="page-item">
                    {% if object_list.has_next %}
                        <a class="page-link" href="?city={{form.cleaned_data.city}}&language={{form.cleaned_data.language}}&page={{ object_list.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}