src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.registration_view, name='registration_view'),
    path('update/', views.update_view, name='update_view'),
    path('delete/', views.delete_view, name='delete_view'),
]

src/scrap/urls.py
from django.urls import path
from . import views

app_name = 'scrap'

urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('list/', views.list_view, name='list_view'),
]

src/work_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls', namespace='scrap')),
    path('', include('accounts.urls', namespace='accounts'))
]

src/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            # date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            # date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    # date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    city = models.ForeignKey('scrap.City', on_delete=models.SET_NULL, null=True, blank=True)
    language = models.ForeignKey('scrap.Language', on_delete=models.SET_NULL, null=True, blank=True)
    send_mail = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    # REQUIRED_FIELDS = ["date_of_birth"]
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import check_password

from scrap.models import City, Language

User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password')

        if email and password:
            qs = User.objects.filter(email=email)
            if not qs.exists():
                raise forms.ValidationError('User does not exists')
            if not check_password(password, qs[0].password):
                raise forms.ValidationError('False password')
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('User is blocked')

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords is not eval')
        return cd['password2']


class UserUpdateForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name='slug', required=False,
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='slug', required=False,
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    send_mail = forms.BooleanField(required=False, widget=forms.CheckboxInput)

    class Meta:
        model = User
        field = ('city', 'language', 'send_mail')

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from accounts.forms import UserLoginForm, UserRegistrationForm, UserUpdateForm

User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd['email']
            password = cd['password']
            user = authenticate(request, email=email, password=password)
            login(request, user)
            return redirect('scrap:home_view')
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('scrap:home_view')


def registration_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            messages.success(request, "Profile has been created.")
            return render(request, 'accounts/register_done.html', {'new_user': new_user})
    else:
        form = UserRegistrationForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/register.html', context=context)


def update_view(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            form = UserUpdateForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user.city = cd['city']
                user.language = cd['language']
                user.send_mail = cd['send_mail']
                user.save()
                messages.success(request, "Profile details updated.")
                return redirect('accounts:update_view')
        else:
            form = UserUpdateForm(initial={'city': user.city, 'language': user.language, 'send_mail': user.send_mail})
            return render(request, 'accounts/update.html', {'form': form})
    else:
        return redirect("accounts:login")


def delete_view(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            qs = User.objects.get(pk=user.pk)
            qs.delete()
            messages.error(request, "An account has been deleted.")
    return redirect('scrap:home_view')

src/accounts/templates/accounts/login.html
{% extends 'scrap/base.html' %}

{% block title %}Login{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form method="POST" action="">
                <div class="mb-3">
                    {{ form.as_p }}
                    {% csrf_token %}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'scrap/base.html' %}

{% block title %}Register{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form method="POST" action="">
                <div class="mb-3">
                    {{ form.as_p }}
                    {% csrf_token %}
                </div>
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/register_done.html
{% extends 'scrap/base.html' %}

{% block title %}Register done{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h4 class="my-2">Welcome {{ new_user.email }}</h4>
            <p>
                You have registered<a href="{% url 'accounts:login_view' %}">Login</a>
            </p>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/update.html
{% extends 'scrap/base.html' %}

{% block title %}Settings{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form method="POST" action="">
                <div class="mb-3">
                    {{ form.as_p }}
                    {% csrf_token %}
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
            <form method="POST" action="{% url 'accounts:delete_view' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger my-3">Delete an account</button>
            </form>
        </div>
    </div>
{% endblock %}